package com.rm.apogee.server

import com.rm.apogee.core.craft.CraftDesign
import com.rm.apogee.core.craft.StockCraft
import com.rm.apogee.core.craft.VesselId
import com.rm.apogee.core.part.PartCatalog
import com.rm.apogee.core.part.StockParts
import com.rm.apogee.core.terrain.TerrainField
import com.rm.apogee.core.world.ClientMessage
import com.rm.apogee.core.world.Command
import com.rm.apogee.core.world.Protocol
import com.rm.apogee.core.world.ServerMessage
import com.rm.apogee.core.world.World
import com.rm.apogee.core.world.WorldEvent
import com.rm.apogee.net.Channel
import com.rm.apogee.net.Codec
import com.rm.apogee.net.Packet
import com.rm.apogee.net.Transport
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import java.util.concurrent.ConcurrentLinkedQueue
import java.util.concurrent.CopyOnWriteArrayList

class ServerConfig(
    val name: String = "Apogee Server",
    /** Simulation rate. Must match the client's prediction rate. */
    val tickHz: Int = 60,
    /**
     * How often vessel motion goes out.
     *
     * Deliberately lower than the tick rate, and deliberately the same over
     * loopback as over a socket. Running loopback at full tick rate would hide
     * every interpolation and prediction problem until the first time two real
     * devices tried to play.
     */
    val snapshotHz: Int = 20,
    /** Craft handed to a player who joins with nothing. */
    val starterCraft: (PartCatalog) -> CraftDesign = { StockCraft.starterRocket(it) },
    /**
     * Whether a player who owns nothing is given [starterCraft] on joining.
     *
     * False when the client is about to launch a craft of its own. Handing it
     * a stock rocket first would leave one standing on the pad in a persistent
     * world every time somebody launched something they had built - debris
     * created by the act of starting properly.
     */
    val assignCraftOnJoin: Boolean = true,
    /**
     * Start every joining player on a fresh [starterCraft], clearing away the
     * craft they flew last time rather than handing it back. Free Flight in
     * single player: a new flight, not a continuation - while the bases a
     * player left elsewhere stay where they are.
     */
    val freshFlight: Boolean = false,
    /**
     * Put a joining player straight into this craft of theirs - Resume Flight,
     * with the craft chosen from a list. Ignored if it is gone or is not
     * theirs.
     */
    val resumeVessel: Long? = null,
    /** Simultaneous players, or 0 for no limit. */
    val maxPlayers: Int = 0,
    /**
     * How lively the weather is, overriding what the world was saved with;
     * null keeps the world's own. The world's seed stays: the same world,
     * calmer or wilder.
     */
    val weatherIntensity: com.rm.apogee.core.weather.WeatherIntensity? = null,
)

/**
 * One connected player.
 *
 * Holds only what the server needs to talk to them and decide what they may
 * do. Note [controlledVessel]: authority is per-vessel, so a command naming a
 * vessel the sender does not own is discarded rather than obeyed. Without that
 * check any client could fly every craft in a persistent world.
 */
class PlayerSession internal constructor(
    val id: Int,
    val transport: Transport,
) {
    @Volatile var playerName: String = "Pilot"
        internal set

    /**
     * Who this player is, as far as the world is concerned.
     *
     * Opaque, generated by the client once per install, never typed. Craft
     * ownership hangs off this rather than off [playerName], which is a label
     * two people can share without noticing - and did, the first time two
     * clients joined the same server as the default "Pilot" and found
     * themselves flying one rocket.
     */
    @Volatile var clientId: String = ""
        internal set

    @Volatile var handshakeComplete: Boolean = false
        internal set

    @Volatile var controlledVessel: VesselId? = null
        internal set

    @Volatile var connected: Boolean = true
        internal set

    suspend fun send(message: ServerMessage, channel: Channel) {
        if (!connected) return
        transport.send(Packet(channel, Codec.encode(message)))
    }
}

/**
 * The authoritative simulation.
 *
 * The same class backs a phone hosting a game for friends and a headless
 * dedicated server; the only difference is which [Transport] the sessions
 * arrive on. Commands are queued as they arrive and applied at tick boundaries,
 * never mid-step, so the result never depends on where in the vessel iteration
 * a packet happened to land.
 */
class GameServer(
    val world: World,
    val config: ServerConfig = ServerConfig(),
) {
    private val sessions = CopyOnWriteArrayList<PlayerSession>()

    init {
        // Every game has weather: set here, before anyone joins, so the
        // welcome can tell each client what to compute.
        val base = world.weatherConfig ?: com.rm.apogee.core.weather.WeatherConfig()
        world.weatherConfig = config.weatherIntensity?.let { base.copy(intensity = it) } ?: base
    }

    /** Names of everyone currently connected, for the admin view. */
    val playerNames: List<String>
        get() = sessions.filter { it.connected && it.handshakeComplete }.map { it.playerName }

    /** Ticks completed since this process started. */
    val tick: Long get() = world.tick
    private val inbox = ConcurrentLinkedQueue<Pair<PlayerSession, ClientMessage>>()
    private var nextSessionId = 1

    val dt: Double = 1.0 / config.tickHz
    private val ticksPerSnapshot: Int = (config.tickHz / config.snapshotHz).coerceAtLeast(1)

    /** Fuel goes to each pilot at a quarter of a second: a gauge, not motion. */
    private val ticksPerFuel: Int = (config.tickHz / FUEL_HZ).coerceAtLeast(1)

    val playerCount: Int get() = sessions.count { it.connected && it.handshakeComplete }

    /**
     * Registers a transport and starts pumping its packets into the inbox.
     *
     * Reading happens on the caller's scope rather than on the simulation loop,
     * so a slow or hostile client can never stall the world.
     */
    fun accept(transport: Transport, scope: CoroutineScope): PlayerSession {
        val session = PlayerSession(nextSessionId++, transport)
        sessions.add(session)

        scope.launch(Dispatchers.Default) {
            try {
                transport.incoming.collect { packet ->
                    val message = runCatching { Codec.decodeClientMessage(packet.bytes) }.getOrNull()
                    // A packet that will not decode is a protocol error, not a
                    // reason to take the server down.
                    if (message != null) inbox.add(session to message)
                }
            } finally {
                session.connected = false
            }
        }
        return session
    }

    fun disconnect(session: PlayerSession) {
        session.connected = false
        session.transport.close()
        sessions.remove(session)
    }

    /**
     * Runs the simulation until the scope is cancelled.
     *
     * Paced against an absolute schedule - each tick is due at a fixed offset
     * from the last - rather than by accumulating elapsed time and sleeping
     * the remainder. Two reasons.
     *
     * Accumulating drifts: every iteration rounds its sleep down to whole
     * milliseconds, and the lost fractions are never paid back. Worse, when
     * the remainder came to less than a millisecond the sleep truncated to
     * zero and the loop spun flat out until the next tick was due. That cost
     * about 6% of a core on a completely empty world, and the same loop runs
     * on the phone when it hosts, where it is battery.
     *
     * With an absolute schedule there is exactly one wake-up per tick, no
     * drift, and an idle server costs almost nothing.
     */
    fun start(scope: CoroutineScope): Job = scope.launch(Dispatchers.Default) {
        val tickNanos = (dt * 1e9).toLong()
        var nextTickAt = System.nanoTime()
        var tickCount = 0L

        while (isActive) {
            val now = System.nanoTime()
            val remainingMillis = (nextTickAt - now) / 1_000_000

            if (remainingMillis >= 1) {
                delay(remainingMillis)
                continue
            }
            // Under a millisecond to go: take the tick now rather than spin
            // for it. At 60Hz that is well under a frame of jitter, and the
            // absolute schedule means it does not accumulate.

            drainInbox()
            runQueuedTasks()
            world.step(dt)
            tickCount++

            publishEvents()
            if (tickCount % ticksPerSnapshot == 0L) broadcastSnapshot()
            if (tickCount % ticksPerFuel == 0L) sendFuel()

            nextTickAt += tickNanos

            // Far enough behind that catching up would mean a burst of ticks
            // each taking longer than real time - a stalled thread, a paused
            // container, a laptop lid. Give up the backlog and resynchronise.
            if (System.nanoTime() - nextTickAt > MAX_CATCHUP_NANOS) {
                nextTickAt = System.nanoTime() + tickNanos
            }
        }
    }

    /** Steps once without any wall-clock pacing. For tests. */
    suspend fun stepOnce() {
        drainInbox()
        runQueuedTasks()
        world.step(dt)
        publishEvents()
        broadcastSnapshot()
        sendFuel()
    }

    private suspend fun drainInbox() {
        while (true) {
            val (session, message) = inbox.poll() ?: return
            handle(session, message)
        }
    }

    private suspend fun handle(session: PlayerSession, message: ClientMessage) {
        when (message) {
            is ClientMessage.Hello -> completeHandshake(session, message)

            is ClientMessage.CommandMessage -> {
                if (!session.handshakeComplete) return
                val command = message.command
                if (!isAuthorised(session, command)) return
                if (command is Command.Chat) {
                    broadcast(
                        ServerMessage.ChatMessage(session.playerName, command.text),
                        Channel.CONTROL,
                    )
                } else if (command is Command.SwitchVessel) {
                    world.apply(command)
                    takeControl(session, VesselId(command.vessel))
                } else if (command is Command.SpawnCraft) {
                    // Launching is how a player gets a *new* craft in a world
                    // they already have one in. Without this the spawn would
                    // land on the pad and they would still be flying whatever
                    // they arrived in - which is what made building a base out
                    // of several launches impossible.
                    val vessel = world.spawnFor(command, session.clientId)
                    vessel.ownerName = session.playerName
                    takeControl(session, vessel.id)
                } else {
                    world.apply(command)
                }
            }
        }
    }

    /**
     * Refuses a mismatched client before it can do any damage.
     *
     * Both checks matter, and they fail differently. A protocol mismatch means
     * the messages themselves will be misread; a catalogue mismatch means they
     * will be read perfectly and mean something else - the client's "tank-cask2"
     * weighs something the server disagrees with, and the two simulations drift
     * apart with no error anywhere. The second is far harder to diagnose from
     * the symptoms, which is exactly why it is checked here.
     */
    private suspend fun completeHandshake(session: PlayerSession, hello: ClientMessage.Hello) {
        if (hello.protocolVersion != Protocol.VERSION) {
            session.send(
                ServerMessage.Rejected(
                    "Protocol mismatch: server speaks ${Protocol.VERSION}, " +
                        "client speaks ${hello.protocolVersion}"
                ),
                Channel.CONTROL,
            )
            disconnect(session)
            return
        }
        if (config.maxPlayers > 0 && playerCount >= config.maxPlayers) {
            // Refused with a reason rather than dropped: a player who cannot
            // tell "server full" from "server broken" will keep retrying.
            session.send(
                ServerMessage.Rejected(
                    "Server is full (${config.maxPlayers} players)"
                ),
                Channel.CONTROL,
            )
            disconnect(session)
            return
        }
        if (hello.catalogHash != world.catalog.contentHash) {
            session.send(
                ServerMessage.Rejected(
                    "Part catalogue mismatch: server has ${world.catalog.contentHash}, " +
                        "client has ${hello.catalogHash}"
                ),
                Channel.CONTROL,
            )
            disconnect(session)
            return
        }
        if (hello.terrainGeneration != TerrainField.GENERATION) {
            session.send(
                ServerMessage.Rejected(
                    "Terrain mismatch: the server's world is terrain generation " +
                        "${TerrainField.GENERATION}, this game has ${hello.terrainGeneration}. " +
                        "Both need the same version of Apogee."
                ),
                Channel.CONTROL,
            )
            disconnect(session)
            return
        }

        session.playerName = hello.playerName.take(32).ifBlank { "Pilot" }
        session.clientId = hello.clientId.take(64)
        if (session.clientId.isBlank()) {
            // Every build that speaks this protocol version sends one, so a
            // blank id is a client that should not have got this far. Refused
            // rather than given an anonymous craft, which would be shared by
            // every other client in the same state.
            session.send(
                ServerMessage.Rejected("Client sent no identity"),
                Channel.CONTROL,
            )
            disconnect(session)
            return
        }
        session.handshakeComplete = true

        // A returning player gets their craft back, wherever they left it.
        // This is what "persistent world" means from the seat: log off in
        // orbit, come back, still be in orbit.
        if (config.freshFlight) {
            world.lastFlown[session.clientId]?.let { last ->
                val previous = world.vessel(VesselId(last))
                if (previous != null && previous.owner == session.clientId) {
                    world.destroy(previous.id, "replaced by a new flight")
                }
            }
        }
        // Resuming one of theirs - or an unowned craft, which becomes theirs:
        // a base from before craft were owned by install, left claimable.
        val chosen = config.resumeVessel?.let { world.vessel(VesselId(it)) }
            ?.takeIf { it.owner == session.clientId || it.owner.isBlank() }
            ?.also { if (it.owner.isBlank()) { it.owner = session.clientId; it.ownerName = session.playerName } }
        val existing = chosen ?: if (config.freshFlight) null else world.vesselOwnedBy(session.clientId)
        // The label follows the player, so renaming yourself renames your
        // craft's owner rather than orphaning it.
        existing?.ownerName = session.playerName
        val vessel = existing ?: if (config.assignCraftOnJoin) {
            // The nearest clear pad, so joining never drops a craft inside one
            // already standing there - not even one left from before a restart.
            world.spawnAtSite(
                config.starterCraft(world.catalog),
                World.launchSites.first(),
            ).also {
                it.owner = session.clientId
                it.ownerName = session.playerName
            }
        } else {
            null
        }
        session.controlledVessel = vessel?.id
        vessel?.let { world.lastFlown[session.clientId] = it.id.raw }

        session.send(
            ServerMessage.Welcome(
                protocolVersion = Protocol.VERSION,
                catalogHash = world.catalog.contentHash,
                serverName = config.name,
                controlledVessel = vessel?.id?.raw ?: -1L,
                weather = world.weatherConfig,
            ),
            Channel.CONTROL,
        )

        // And what has been knocked down, so their forest matches everyone's.
        if (world.felledScatter.isNotEmpty()) {
            session.send(ServerMessage.ScatterFelled(world.felledScatter.toList()), Channel.STRUCTURE)
        }

        // A joining client needs the structure of everything already out there,
        // not just its own craft, or every other player is invisible until
        // something about them happens to change.
        for (existing in world.vessels) {
            session.send(
                ServerMessage.StructureMessage(world.structureUpdateFor(existing)),
                Channel.STRUCTURE,
            )
        }
        session.send(ServerMessage.SnapshotMessage(world.snapshot()), Channel.KINEMATICS)
    }

    private val tasks = ConcurrentLinkedQueue<() -> Unit>()

    /**
     * Runs [task] on the tick thread, between two steps - where the world is
     * whole, rather than whenever the calling thread happens to catch it. A
     * save taken from another thread mid-step could record half a tick, or
     * trip over the vessel map changing under it.
     */
    fun runBetweenTicks(task: () -> Unit) {
        tasks.add(task)
    }

    private fun runQueuedTasks() {
        while (true) {
            val task = tasks.poll() ?: return
            task()
        }
    }

    /** Moves a session's control to [id] and tells the client about it. */
    private suspend fun takeControl(session: PlayerSession, id: VesselId) {
        session.controlledVessel = id
        world.lastFlown[session.clientId] = id.raw
        session.send(ServerMessage.ControlChanged(id.raw), Channel.CONTROL)
    }

    private fun isAuthorised(session: PlayerSession, command: Command): Boolean = when (command) {
        is Command.SetThrottle -> session.controlledVessel?.raw == command.vessel
        is Command.SetAttitude -> session.controlledVessel?.raw == command.vessel
        is Command.SetSas -> session.controlledVessel?.raw == command.vessel
        is Command.SetBrakes -> session.controlledVessel?.raw == command.vessel
        is Command.SetTranslation -> session.controlledVessel?.raw == command.vessel
        is Command.SetRcs -> session.controlledVessel?.raw == command.vessel
        is Command.Stage -> session.controlledVessel?.raw == command.vessel
        // Welding consumes the *other* craft, which may belong to someone
        // else. Only the craft being flown may initiate it, and the world
        // still refuses unless the two are touching and at rest - but this is
        // the line to revisit when bases get owners worth defending.
        is Command.Join -> session.controlledVessel?.raw == command.vessel
        // Only your own craft. Anything else and a player could take the
        // controls of somebody else's base on a shared server.
        is Command.SwitchVessel ->
            world.vessel(VesselId(command.vessel))
                ?.owner == session.clientId
        is Command.SpawnCraft -> true
        is Command.Chat -> true
    }

    private suspend fun publishEvents() {
        for (event in world.drainEvents()) {
            when (event) {
                is WorldEvent.VesselSpawned ->
                    world.vessel(event.id)?.let {
                        broadcast(
                            ServerMessage.StructureMessage(world.structureUpdateFor(it)),
                            Channel.STRUCTURE,
                        )
                    }

                is WorldEvent.VesselStructureChanged ->
                    world.vessel(event.id)?.let {
                        broadcast(
                            ServerMessage.StructureMessage(world.structureUpdateFor(it)),
                            Channel.STRUCTURE,
                        )
                    }

                is WorldEvent.VesselDestroyed ->
                    broadcast(
                        ServerMessage.StructureMessage(
                            com.rm.apogee.core.world.StructureUpdate(event.id.raw, design = null)
                        ),
                        Channel.STRUCTURE,
                    )

                // Staging changes which parts are live and which stage is
                // next, and both live in the structure message. Without this
                // the client's stage counter and engine-lit state go stale the
                // moment anything is staged that does not also separate.
                is WorldEvent.Staged ->
                    world.vessel(event.id)?.let {
                        broadcast(
                            ServerMessage.StructureMessage(world.structureUpdateFor(it)),
                            Channel.STRUCTURE,
                        )
                    }

                is WorldEvent.Touchdown -> Unit

                is WorldEvent.ScatterFelled ->
                    broadcast(ServerMessage.ScatterFelled(listOf(event.scatterId)), Channel.STRUCTURE)

                // A failed part changes what the craft can still do, and that
                // lives in the structure message alongside staging.
                is WorldEvent.PartFailed ->
                    world.vessel(event.id)?.let {
                        broadcast(
                            ServerMessage.StructureMessage(world.structureUpdateFor(it)),
                            Channel.STRUCTURE,
                        )
                    }

                is WorldEvent.LightningHit ->
                    broadcast(ServerMessage.Lightning(event.strikeId, event.id.raw, event.partIndex), Channel.STRUCTURE)
            }
        }
    }

    /**
     * Sends a chat line from the server itself.
     *
     * Public because the dedicated server's admin channel needs to talk to the
     * people playing - an operator announcing a restart is the single most
     * useful thing an admin panel does.
     */
    suspend fun broadcastChat(from: String, text: String) =
        broadcast(ServerMessage.ChatMessage(from, text), Channel.CONTROL)

    /** Finds a connected player by name, for admin actions. */
    fun sessionNamed(playerName: String): PlayerSession? =
        sessions.firstOrNull {
            it.connected && it.handshakeComplete && it.playerName.equals(playerName, ignoreCase = true)
        }

    private suspend fun broadcastSnapshot() {
        if (sessions.isEmpty()) return
        val snapshot = world.snapshot()
        broadcast(ServerMessage.SnapshotMessage(snapshot), Channel.KINEMATICS)
    }

    /** Each pilot's own tanks. */
    private suspend fun sendFuel() {
        for (session in sessions) {
            if (!session.connected || !session.handshakeComplete) continue
            val vessel = session.controlledVessel?.let { world.vessel(it) } ?: continue
            session.send(ServerMessage.FuelLevels(vessel.id.raw, vessel.flatResources()), Channel.KINEMATICS)
        }
    }

    private suspend fun broadcast(message: ServerMessage, channel: Channel) {
        for (session in sessions) {
            if (session.connected && session.handshakeComplete) session.send(message, channel)
        }
    }

    companion object {
        private const val MAX_CATCHUP_NANOS = 250_000_000L
        private const val FUEL_HZ = 4

        fun default(catalog: PartCatalog = StockParts.catalog, config: ServerConfig = ServerConfig()) =
            GameServer(World.default(catalog), config)
    }
}
